### ISSUE TITLE
package v2.0.5 in npm doesn't consist with github.

### ISSUE THREAD

**Issue by jkvim** [weflex/neaty-component-passport#2]
node_module file does not consist with the newest github file.

local version: v2.0.5

btw, are you forgot to modify the version in package.json?

**Comment by yorkie** [comment]
Yea, because your local patch is a hotfix, 2.0.5 is complete fix.

**Comment by jkvim** [comment]
i have try reinstall and still not consist.

**Comment by yorkie** [comment]
What do you mean by the consistent?
