### ISSUE TITLE
Error on v2.0.5

### ISSUE THREAD

**Issue by jkvim** [weflex/neaty-component-passport#3]
cause error after install v2.0.5,

> TypeError: Cannot read property 'authenticate' of undefined
>     at Authenticator.authenticate (/Users/jkvim/weflex/gateway/node_modules/passport/lib/authenticator.js:167:25)
>     at /Users/jkvim/weflex/gateway/node_modules/neaty-component-passport/lib/passport-configurator.js:514:7
>     at Layer.handle [as handle_request](/Users/jkvim/weflex/gateway/node_modules/express/lib/router/layer.js:95:5)
>     at next (/Users/jkvim/weflex/gateway/node_modules/express/lib/router/route.js:131:13)
>     at Route.dispatch (/Users/jkvim/weflex/gateway/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request](/Users/jkvim/weflex/gateway/node_modules/express/lib/router/layer.js:95:5)
>     at /Users/jkvim/weflex/gateway/node_modules/express/lib/router/index.js:277:22
>     at Function.process_params (/Users/jkvim/weflex/gateway/node_modules/express/lib/router/index.js:330:12)
>     at next (/Users/jkvim/weflex/gateway/node_modules/express/lib/router/index.js:271:10)
>     at urlencodedParser (/Users/jkvim/weflex/gateway/node_modules/body-parser/lib/types/urlencoded.js:91:37)
>     at /Users/jkvim/weflex/gateway/node_modules/body-parser/index.js:91:7
>     at jsonParser (/Users/jkvim/weflex/gateway/node_modules/body-parser/lib/types/json.js:103:37)
>     at bodyParser (/Users/jkvim/weflex/gateway/node_modules/body-parser/index.js:89:5)
>     at Layer.handle [as handle_request](/Users/jkvim/weflex/gateway/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/jkvim/weflex/gateway/node_modules/express/lib/router/index.js:312:13)
>     at /Users/jkvim/weflex/gateway/node_modules/express/lib/router/index.js:280:7

**Comment by yorkie** [comment]
How to reproduce this crash?

**Comment by jkvim** [comment]
when i use phone login in wechat, it occur.

**Comment by yorkie** [comment]
Try with 2.1.0 again, thanks

**Comment by jkvim** [comment]
still has same error on 2.1.0, may be my code error?

**Comment by yorkie** [comment]
Try 2.1.1 which fix the scope problem
